USE [ToDo]

GO

CREATE TABLE [AccountsLists]
(
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    AccountID UNIQUEIDENTIFIER,
    ListID UNIQUEIDENTIFIER,
    Role TINYINT NOT NULL,
    FOREIGN KEY (AccountID) REFERENCES Accounts (ID),
)

GO