Invoke-Sqlcmd -InputFile DropDataBase.sql
Invoke-Sqlcmd -InputFile ToDo.sql
Invoke-Sqlcmd -InputFile Plans.sql
Invoke-Sqlcmd -InputFile PlanData.sql
Invoke-Sqlcmd -InputFile Account.sql
Invoke-Sqlcmd -InputFile TodoLists.sql
Invoke-Sqlcmd -InputFile TodoListItems.sql
Invoke-Sqlcmd -InputFile TodoListLayouts.sql
Invoke-Sqlcmd -InputFile SubItems.sql
Invoke-Sqlcmd -InputFile SubItemLayouts.sql
Invoke-Sqlcmd -InputFile Discounts.sql
Invoke-Sqlcmd -InputFile DiscountsData.sql
Invoke-Sqlcmd -InputFile AccountsDiscounts.sql
Invoke-Sqlcmd -InputFile AccountsLists.sql
Invoke-Sqlcmd -InputFile AccountsPlans.sql
Invoke-Sqlcmd -InputFile PaymentMethods.sql
Invoke-Sqlcmd -InputFile Downgrades.sql