USE ToDo

GO

Create TABLE [SubItemLayouts](
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    AccountID UNIQUEIDENTIFIER,
    ItemId UNIQUEIDENTIFIER,
    Layout VARCHAR(max) NOT NULL,
    FOREIGN KEY (ItemId) REFERENCES TodoListItems (ID) ON DELETE CASCADE,
     UNIQUE (ItemId)
)

GO