USE [ToDo]

GO

CREATE TABLE [TodoListItems](
    [ID] UNIQUEIDENTIFIER PRIMARY KEY,
    [AccountID] UNIQUEIDENTIFIER,
    [Notes] VARCHAR(200),
    [Completed] BIT NOT NULL DEFAULT(0),
    [Name] VARCHAR(50),
	[DueDate] DATETIME,
    [ListID] UNIQUEIDENTIFIER,

    FOREIGN KEY (ListID) REFERENCES TodoLists (ID) ON DELETE CASCADE
)

GO